version: '3.8'

services:
  frontend:
    build:
      context: ./apps/frontend
    env_file:
      - .env.frontend
    restart: always

  backend:
    build:
      context: ./apps/backend
    env_file:
      - .env.backend
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=poizon
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgres-data: 