version: '3.8'

services:
  frontend:
    build:
      context: ./apps/frontend
      target: builder
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.frontend
    command: npm run dev

  backend:
    build:
      context: ./apps/backend
      target: builder
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.backend
    command: npm run start:dev
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=poizon
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 